### ISSUE TITLE
cashondelivery fee not in totals

### ISSUE THREAD

**Issue by Kamik** [PHOENIX-MEDIA/Magento-CashOnDelivery#15]
Hi,
we have one step checkout from mage-world.
And delivery fee is not added to the total. What can be wrong?

**Comment by peibelx** [comment]
I'm on the same situation. Everything during installation seems to be ok but no info is added to the summary and no extra fee added.

**Comment by q23** [comment]
any news on this her?

**Comment by q23** [comment]
this is working for us like a charm
http://www.magentocommerce.com/magento-connect/cash-on-delivery-3.html

**Comment by PHOENIX-MEDIA** [comment]
You would have to look at the OSC extension yourself, as maybe the OSC extension changes the behaviour of totals.
