### ISSUE TITLE
COD fee not changeable on creditmemo

### ISSUE THREAD

**Issue by J0s3f** [PHOENIX-MEDIA/Magento-CashOnDelivery#16]
When issuing a credit, it is not possible to change the COD fee.
Sometimes only a part of the order shall be credited, and the fee for the COD should not be part of the credit!
This is currently not possible!

**Comment by PHOENIX-MEDIA** [comment]
It is now possible to change the credit memo CoD fee do so.

**Comment by lafadot** [comment]
Sorry but how can I change the COD fee on credit memo?
this is what I see when creating a credit memo. No way to edit COD fee. I just pulled last version

![cod](https://user-images.githubusercontent.com/8129390/37174811-f3ed3db2-2317-11e8-8f1b-fda1fa19e5ec.png)
