### ISSUE TITLE
COD Fee in Order Emails

### ISSUE THREAD

**Issue by seangreen** [PHOENIX-MEDIA/Magento-CashOnDelivery#24]
Hi.

The COD fee is not being displayed in the summary of the order emails - but in the invoices it is displayed just fine. The fee is being displayed correctly under "payment type", but not below in summary + taxes.
Is there something I have to do, to display them in the emails, or is that currently not possible?

(I assume it should be possible, since in the changelog it says:
0.4.1:
Added COD fee in order and invoice emails (thanks to Kristof Ringleff)
- or is that something different?

Thanks,
Sean.

**Comment by PHOENIX-MEDIA** [comment]
Seems to be resolved by now.
