### ISSUE TITLE
In which table is stored

### ISSUE THREAD

**Issue by kousinontre** [PHOENIX-MEDIA/Magento-CashOnDelivery#32]
I'm coming again to ask in which table the cash on delivery saved. Not the configuration of the module but in the order of the customer.
I'm trying to make a query to the database to find the order and if it has cash on delivery charge so to add it to my program

**Comment by PHOENIX-MEDIA** [comment]
Depends on the magento version. There is a payment_method column which identifies orders which have been placed using this payment option (check sales_flat_order_payment).
