### ISSUE TITLE
Problem with Maximum Order Total - possible bug

### ISSUE THREAD

**Issue by ktsixit** [PHOENIX-MEDIA/Magento-CashOnDelivery#35]
Hi,
I'm using this extension in my website. I have set 'Maximum Order Total = 74.99' in configuration.
I'd like this payment method to be available only for orders with subtotal less than 75euros.

The problem is that if the user has selected a SHIPPING method that has fee (in my case shipping cost is 2euros), that fee is added to the subtotal and makes the payment method not available.

For example, there's a customer who has added some products to the cart. The subtotal is 74.40euro + 2 euro for shipping costs.
The CashOnDelivery method is becoming not-available because it thinks that subtotal is 76.40euro and not 74.40.

How can I fix that?

**Comment by PHOENIX-MEDIA** [comment]
This is a general Magento payment method configuration. Nothing has been overwritten by us. So you would need to change how `max_order_total` is handled by Magento itself.
