### ISSUE TITLE
Problem with multi website 

### ISSUE THREAD

**Issue by oblomova80** [PHOENIX-MEDIA/Magento-CashOnDelivery#37]
The Cash on delivery doesn't work on website other than the default. It doesn't appear among the payment methods, in onepage checkout.

**Comment by PHOENIX-MEDIA** [comment]
Please check your settings. Maybe some other settings prevent the payment method from being listed. We tested ChasOnDelivery on a multi website environment right now and the payment method appeared on both websites in onepage checkout.
