### ISSUE TITLE
checkout php Error

### ISSUE THREAD

**Issue by jtrakadas** [PHOENIX-MEDIA/Magento-CashOnDelivery#39]
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Phoenix\\CashOnDelivery\\Model\\Total\\Tax\\Quote::_clearValues() must be of the type array, object given, called in /data/www/vendor/phoenix/module-cashondelivery/Model/Total/Tax/Quote.php on line 94 and defined in /data/www/vendor/phoenix/module-cashondelivery/Model/Total/Tax/Quote.php:119\nStack trace:\n#0 /data/www/vendor/phoenix/module-cashondelivery/Model/Total/Tax/Quote.php(94): Phoenix\\CashOnDelivery\\Model\\Total\\Tax\\Quote->_clearValues(Object(Magento\\Quote\\Model\\Quote), Object(Magento\\Quote\\Model\\Quote\\Address\\Total), Object(Phoenix\\CashOnDelivery\\Model\\Total\\Tax\\Quote))\n#1 /data/www/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(265): Phoenix\\CashOnDelivery\\Model\\Total\\Tax\\Quote->collect(Object(Magento\\Quote\\Model\\Quote), Object(Magento\\Quote\\Model\\ShippingAssignment), Object(Magento\\Quote\\Model\\Quote\\Address\\Total))\n#2 /data/www/vendor/magento/module-quote/Model/ShippingMethodManagement.php(288): Magento\\Quote\\Model\\Quote\\TotalsCollector->collectAddress in /data/www/vendor/phoenix/module-cashondelivery/Model/Total/Tax/Quote.php on line 119

**Comment by PHOENIX-MEDIA** [comment]
We identified the problem, but this is an issue with the magento 2 version. Please reopen the issue in the correct repository.
