### ISSUE TITLE
Email confirm order missing payment 

### ISSUE THREAD

**Issue by pigorg** [PHOENIX-MEDIA/Magento-CashOnDelivery#40]
Hi.

In confirm order email missing the cash on delivery method. There is a white space

![metodo](https://user-images.githubusercontent.com/15121381/33016315-5d77876c-cdee-11e7-8615-120689de0dea.jpg)

How i can to fix this problem?

Thanks

**Comment by PHOENIX-MEDIA** [comment]
Hi! Is it possible that you are using a different email template or that you have no title and custom text for the payment method configured?
