### ISSUE TITLE
foreigncosts should be foreigncountrycosts

### ISSUE THREAD

**Issue by kendertas** [PHOENIX-MEDIA/Magento-CashOnDelivery#42]
File
app/code/community/Phoenix/CashOnDelivery/Model/CashOnDelivery.php

Method
getForeignCountryCosts()

It's using "foreigncosts", but in configuration "system.xml", it's called "foreigncountrycosts"

**Comment by PHOENIX-MEDIA** [comment]
This issue has been resolved in the last commit and will be available in the next release.
