### ISSUE TITLE
Magento Connect installation failed for PHP > 7.0.22

### ISSUE THREAD

**Issue by francymin** [PHOENIX-MEDIA/Magento-CashOnDelivery#44]
Hello,
when I try to install the package from Magento Connect Manager, I got this error message:

`CONNECT ERROR: Package da24aca8d7c5b9212ecc5b76646c8df3/phoenix+CashOnDelivery 1.0.10: requires PHP version >= 5.2.0 and <= 7.0.22 current is: 7.0.26`

Can I install this manually? Or I have to take the information seriously?

**Comment by PHOENIX-MEDIA** [comment]
We had to enter a version and the latest one was 7.0.22 at the time we build the package. We also noticed that this will cause problems when updating php. We will change this. Meanwhile you can download the package from marketplace or github and install it manually.

**Comment by PHOENIX-MEDIA** [comment]
New version available on Magento Marketplace!
