### ISSUE TITLE
COD charge conflict with Shopping cart price Rules 

### ISSUE THREAD

**Issue by semsem79** [PHOENIX-MEDIA/Magento-CashOnDelivery#45]
HI ,
The COD Charge is still appearing after reaching the ( free delivery amount ) in the cart .

Ex:
- Fixed shipping charge = 10 $
- Shipping charge after 200 $ = Zero
- Cash On Delivery Charge = 5 $ extra
  - Error : even after 200$ , COD charge is still appearing .

Please update how to solve this .

Thanks

**Comment by semsem79** [comment]
No one to help in this issue ?

**Comment by PHOENIX-MEDIA** [comment]
The cash on delivery fee is NOT a shipping method. The fee for the payment method is collected by the shipping carrier on delivery together with the payable order amount and has nothing to do with the shipping amount.
