### ISSUE TITLE
Wrong currency code in totals ( order creation )

### ISSUE THREAD

**Issue by postadelmaga** [PHOENIX-MEDIA/Magento-CashOnDelivery#49]
Module Version:  1.0.11

During order creation:
- The COD total displayed is displayed with the wrong currency, I have tested only in the backend but It is the same issue is probably also on frontend.

Note that: After the order is submitted, the order details page **COD currency code is correct.**

see ( order creation ):
![total_issue](https://user-images.githubusercontent.com/2010800/37887224-34469a64-30f3-11e8-95bc-c9025c1908b2.png)
 
Here the currency settings for the store view related to the above order  
![currency](https://user-images.githubusercontent.com/2010800/37887229-377714c0-30f3-11e8-9f3b-7f2a1110bce2.png)

Here my COD settings
![cod_settings](https://user-images.githubusercontent.com/2010800/37887231-39730658-30f3-11e8-9c8d-ab9f49010e90.png)

**Comment by PHOENIX-MEDIA** [comment]
What is your exact currency setup? Do you have different currencies for different configuration scopes? Where can the dollar setting come from?

**Comment by postadelmaga** [comment]
@PHOENIX-MEDIA 
Yes I have different currency for different store view:
-> Default scope -> EUR
-> USA storeview -> USD
-> Italian storeview -> EUR
-> Australian storeview -> AUD
..

**Comment by PHOENIX-MEDIA** [comment]
Thanks for the tip!

**Comment by postadelmaga** [comment]
You are welcome :)
